@startuml
actor Amministratore
participant AmmPanel
participant RegistrazioneUtentePanel
participant FacadeController
participant RSAService
participant FacadeSingletonDB
database MYSql

Amministratore --> AmmPanel
activate AmmPanel

AmmPanel --> RegistrazioneUtentePanel : setVisible(true)
deactivate AmmPanel
activate RegistrazioneUtentePanel
RegistrazioneUtentePanel --> FacadeController : inserimento anagrafica
deactivate RegistrazioneUtentePanel
activate FacadeController
FacadeController --> RSAService: registraUtente()
deactivate FacadeController
activate RSAService
RSAService --> FacadeSingletonDB : registraUtente()
deactivate RSAService
activate FacadeSingletonDB
FacadeSingletonDB --> MYSql : insertPersona()\n insertCartellaClinica()
deactivate FacadeSingletonDB





@enduml